# Generated by Django 5.0.6 on 2024-05-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='addresseClient',
            field=models.TextField(default='casablanca'),
            preserve_default=False,
        ),
    ]
