# Generated by Django 5.0.6 on 2024-06-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_client_remove_commandeitem_commande_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='addresse',
            new_name='adresseF',
        ),
    ]
