# Generated by Django 5.0.6 on 2024-07-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_commande_produitcommande_delete_commandeproduit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='id',
            new_name='idC',
        ),
        migrations.RenameField(
            model_name='produitcommande',
            old_name='id',
            new_name='idPC',
        ),
    ]
